### ISSUE TITLE
Can't find the EfficientNet module in mask_rcnn.py!

### ISSUE THREAD

**Issue by chenfsjz** [dvl-tum/e-osvos#1]
hi!
I find there are some issues in train_parent.py. I can't find the related modules of EfficientNet.
Could you provide them!
Thank your!

**Comment by timmeinhardt** [comment]
Hello, the EfficientNet references should not be in the repository. I removed them and hopefully now it should work. Best, Tim

**Comment by chenfsjz** [comment]
ok! Thank you!

**Comment by chenfsjz** [comment]
Ｉ have successfully rerun the train process. A problem is that the evaluate applies the DAVIS dataset which requires train_seqs, val_seqs, and test-dev_seqs split files. Does these split files generate by your own strategy?

**Comment by timmeinhardt** [comment]
Thank you for pointing this out. I just pushed the missing sequences files to the `data` folder.

**Comment by timmeinhardt** [comment]
Can we close this issue?
